task:
  env:
    matrix:
      VERSION: 1.15
      # VERSION: 1.14
  name: Tests (Go $VERSION)
  # container:
  #   image: golang:$VERSION
  macos_instance:
    image: big-sur-base
  build_script: uname -s; go version
